### ISSUE TITLE
Search entry not centered

### ISSUE THREAD

**Issue by zagortenay333** [Feuerfuchs/GPaste-Reloaded-Cinnamon-Applet#1]
I would really like seeing it centered or stretched across the whole width of the popup if possible.

**Comment by Feuerfuchs** [comment]
Thanks for the suggestion! That actually annoys me, too, but I couldn't find a fix in time (I've been away for a week) and thus released it like that. I'll try to fix it in the next few days.

**Comment by Feuerfuchs** [comment]
6423ca6ae068900ec9f229e5a81aa45888aa0cdd fixes this issue.

**Comment by zagortenay333** [comment]
Sweet!
