### ISSUE TITLE
Search not working

### ISSUE THREAD

**Issue by zagortenay333** [Feuerfuchs/GPaste-Reloaded-Cinnamon-Applet#2]
Just noticed that the search doesn't work here. Any special package I need to install?

**Comment by Feuerfuchs** [comment]
What GPaste version do you use?

**Comment by zagortenay333** [comment]
1.3

**Comment by Feuerfuchs** [comment]
No, I mean the GPaste Daemon. ;) You can find that out quickly by running "gpaste version".

**Comment by zagortenay333** [comment]
Oh lol. It's 3.10.4

**Comment by Feuerfuchs** [comment]
Oh, that's rather old. I guess the search feature hadn't been implemented yet in that version. Nothing I can fix, unfortunately. :/
If you really want that search feature to work, you may go to GPaste's GitHub and compile the latest version yourself.
What I will do is to hide the search bar permanently for all version of GPaste that don't support this feature yet.

**Comment by zagortenay333** [comment]
Ah. Mint is behind the times in this regard... :disappointed:

**Comment by Feuerfuchs** [comment]
Alright, the dev build now contains a version check for the search bar. If you test it, you won't see the search bar regardless of your applet settings.

**Comment by zagortenay333** [comment]
Thx!
