### ISSUE TITLE
[[feature]] – Be Able to Delete History Items from the Menu Via Key Command

### ISSUE THREAD

**Issue by 4tuw2tuv0** [Feuerfuchs/GPaste-Reloaded-Cinnamon-Applet#7]
Pretty much as the title describes. I believe the original GPaste applet had the capability and I like being able to use my OS entirely with just the keyboard so the feature is appealing.

I tried to figure out how to do it so I could do it myself and then put in a pull request but I know very little about making applets to begin with and the documentation doesn't seem particularly forthcoming (that or I cannot find the appropriate doc.). I figured I'd, at least, log the issue and you might know better than I (your code looks like you seem to have a fairly in-depth grasp of applet-making).

**Comment by Feuerfuchs** [comment]
In v2.4, you can remove an item using the delete or backspace key. Thanks for the suggestion!

**Comment by 4tuw2tuv0** [comment]
Super cool! Tested it out and it's super great to use. Thanks so much!
